config_version: env1_2d_vgg16_fc2_9_avgmax

unity_env: env1
model_name: vgg16
output_layer: fc2
n_components: 9
movement_mode: 2d
reduction_method: avgmax
n_rotations: 6

# unity settings
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
