config_version: env15fixed_2d_vgg16_fc2_9_pca

unity_env: env15fixed
model_name: vgg16
output_layer: fc2
n_components: 9
movement_mode: 2d
reduction_method: pca
n_rotations: 6

# unity settings
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
