config_version: env28_r24_2d_vit_b16_layer_6
unity_env: env28_r24
model_name: vit_b16
output_layer: layer_6
movement_mode: 2d
n_rotations: 24
env_x_min: -4
env_x_max: 4
env_y_min: -4
env_y_max: 4
multiplier: 2
