config_version: env23_r24_2d_none_raw_9_maxvar
unity_env: env23_r24
model_name: none
output_layer: raw
n_components: 9
movement_mode: 2d
reduction_method: maxvar
n_rotations: 24
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
