config_version: env28_r24_2d_vgg16_b5p
unity_env: env28_r24
model_name: vgg16
output_layer: block5_pool
movement_mode: 2d
n_rotations: 24
env_x_min: -4
env_x_max: 4
env_y_min: -4
env_y_max: 4
multiplier: 2
feature_selection: full
