config_version: env28_r24_2d_vit_b16_untrained_layer_9
unity_env: env28_r24
model_name: vit_b16_untrained
output_layer: layer_9
movement_mode: 2d
n_rotations: 24
env_x_min: -4
env_x_max: 4
env_y_min: -4
env_y_max: 4
multiplier: 2
