config_version: env28_r24_2d_simclrv2_r50_1x_sk0_final_avg_pool_full
unity_env: env28_r24
model_name: simclrv2_r50_1x_sk0
output_layer: final_avg_pool
movement_mode: 2d
n_rotations: 24
env_x_min: -4
env_x_max: 4
env_y_min: -4
env_y_max: 4
multiplier: 2
feature_selection: full
