config_version: env28_r24_2d_resnet50_untrained_conv2_block3_out
unity_env: env28_r24
model_name: resnet50_untrained
output_layer: conv2_block3_out
movement_mode: 2d
n_rotations: 24
env_x_min: -4
env_x_max: 4
env_y_min: -4
env_y_max: 4
multiplier: 2
