config_version: env28_r24_2d_vgg16_untrained_block2_pool
unity_env: env28_r24
model_name: vgg16_untrained
output_layer: block2_pool
movement_mode: 2d
n_rotations: 24
env_x_min: -4
env_x_max: 4
env_y_min: -4
env_y_max: 4
multiplier: 2
