config_version: env21_2d_vgg16_fc2_9_pca

unity_env: env21
model_name: vgg16
output_layer: fc2
n_components: 9
movement_mode: 2d
reduction_method: pca
n_rotations: 1

# unity settings
x_min: -12
x_max: 12
y_min: -12
y_max: 12
multiplier: 3
