config_version: env33_r24_2d_none_raw_9_nmf
unity_env: env33_r24
model_name: none
output_layer: raw
n_components: 9
movement_mode: 2d
reduction_method: nmf
n_rotations: 24
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
