config_version: env6_2d_none_uniform999_9_pca

unity_env: env6
model_name: none
output_layer: uniform999
n_components: 9
movement_mode: 2d
reduction_method: pca
n_rotations: 6
random_seed: 999

# unity settings
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
