config_version: env8_2d_vgg16_block2_pool_9_nmf

unity_env: env8
model_name: vgg16
output_layer: block2_pool
n_components: 9
movement_mode: 2d
reduction_method: nmf
n_rotations: 6

# unity settings
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
