config_version: env8_2d_vgg16_fc1_9_pca

unity_env: env8
model_name: vgg16
output_layer: fc1
n_components: 9
movement_mode: 2d
reduction_method: pca
n_rotations: 6

# unity settings
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
