config_version: env9_2d_none_raw_9_ica

unity_env: env9
model_name: none
output_layer: raw
n_components: 9
movement_mode: 2d
reduction_method: ica
n_rotations: 1

# unity settings
x_min: -4
x_max: 4
y_min: -4
y_max: 4
multiplier: 2
